# Site settings
title: Lynn A. Conway Memorial Scholarship
description: >-
  The Lynn A. Conway Memorial Scholarship supports LGBTQ+ students in STEM
  at the University of Michigan, honoring the legacy of a pioneering computer
  scientist and transgender rights advocate.
tagline: Honoring a pioneer in computer science and champion of LGBTQ+ inclusion in STEM
url: "https://conwayscholarship.org"
baseurl: ""
lang: en_US

# Open Graph / Social
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/lynn-conway-um-portrait-cropped.jpg


# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - preview.html

# Optional: Enable future posts
future: true

# Plugins (GitHub Pages supported)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
